### ISSUE TITLE
Version 4.0 release

### ISSUE THREAD

**Issue by dotherightthing** [Tipue/Tipue-drop#1]
If version 4.0 is stable can you please add a 4.0 release/tag so that I can pull down the latest code using Bower?

For now I'll use the commit SHA.

Thanks,
Dan

**Comment by Tipue** [comment]
Sorry, but I'm not sure what you mean.

**Comment by dotherightthing** [comment]
If you look at the Tipue Drop's (Github) [Releases page](https://github.com/Tipue/Tipue-drop/releases), there's just one 'tagged' [release](https://help.github.com/articles/about-releases/) - [`3.1.0` from Dec 4 2013](https://github.com/Tipue/Tipue-drop/releases/tag/3.1.0).

By referencing the `3.1.0` release or 'tag', users of Package Managers such as NPM and Bower can include your plugin in their own projects. This will pull down the plugin files as they stood on Dec 4 2013.

When I look at Tipue Drop's Githib commit history, I can see a number of commits from 10 months ago. These were committed with the message *Version 4.0*. Given the age of these commits and that the code in this 'version' matches the code on [your demo page](http://www.tipue.com/drop/), it leads me to believe that *Version 4.0* is the latest stable version of Tipue Drop.

So if you now [create a release](https://help.github.com/articles/creating-releases/) called `4.0.0` this will allow users of your plugin to pull the *Version 4.0* code rather than the version `3.1.0` code.

Cheers,
Dan

**Comment by Tipue** [comment]
Thanks. Now done.

**Comment by dotherightthing** [comment]
Good stuff, thanks!
