### ISSUE TITLE
Open result page in parent frame 

### ISSUE THREAD

**Issue by kawish** [Tipue/Tipue-drop#2]
I am using tipue drop inside an IFRAME on www.medcare4u.com 

Currently when we click on a drop down item , it opens the result page in a new tab 

BUT I WANT 
to open the result page on the same parent window 
(Not inside the IFRAME)
(Not in a new tab)

**Comment by Tipue** [comment]
Edit the target value in line 69 of the script.

**Comment by kawish** [comment]
Please specify the name of the file and the value which should be put in line no 69

**Comment by Tipue** [comment]
The file is the main script, tipuedrop.js, and the target attribute value will probably be _parent.
